blank_issues_enabled: true
contact_links:
  - name: Documentação da Entrega 03
    url: https://unbarqdsw2026-2-turma01.github.io/2026.2-T01-_G6_ProjetoStreamingVideo_Entrega_03/
    about: Introdução, relatórios e participações do Grupo 06.
